export class ConstantsApp{
    public static NOME_SECRETARIA = "SECRETARIA DA AGRICULTURA, PECUÁRIA E DESENVOLVIMENTO RURAL";
    public static NOME_DEPARTAMENTO = "DEPARTAMENTO DE DEFESA AGROPECUÁRIA"
}